
const brawlers = {
    "Squeak": {
        "id": 564817680225875,
        "name": "Squeak",
        "health": 3360,
        "attack": 1620,
        "range": 7.67,
        "reload": "2.1 seconds",
        "movement": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/c/cf/Squeak_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/0/04/Squeak_Portrait.png"
    },
    "Poco": {
        "id": 270241425941586,
        "name": "Poco",
        "health": 6000,
        "attack": 1140,
        "range": 7,
        "reload": "1.6 seconds",
        "movement": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/2/24/Poco_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/5/59/Poco_Portrait.png"
    },
        "Pam": {
            "id": 7503072122885093,
            "name": "Pam",
            "health": 7200,
            "attack": "390(9)",
            "range": 9,
            "reload": "1.3 seconds",
            "movement": 720,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/68/Pam_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/d/dc/Pam_Portrait.png"
    },
        "Griff": {
            "id": 3322223126098713,
            "name": "Griff",
            "health": 5100,
            "attack": "390(9)",
            "range": 8.33,
            "reload": "1.7 seconds",
            "movement": 720,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/0/0f/Griff_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/c/c9/Griff_Portrait.png"
    },
        "Rico": {
            "id": 3322223126098723,
            "name": "Rico",
            "health": 4200,
            "attack": "480(5)",
            "range": 9.67,
            "reload": "1.2 seconds",
            "movement": 720,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/7/71/Rico_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/e/e1/Rico_Portrait.png"
    },
        "Barley": {
            "id": 5912603130654450,
            "name": "Barley",
            "health": 3600,
            "attack": "1140(2)",
            "range": 7.33,
            "reload": "2.0 seconds",
            "movement": 720,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/3/3c/Barley_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/a/a1/Barley_Portrait.png"
    },
        "Frank": {
            "name": "Frank",
            "id": 1186200347652610,
            "health": 10500,
            "attack": 1860,
            "range": 6,
            "reload": "0.8 seconds",
            "movement": 770,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/5/55/Frank_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/6/63/Frank_Portrait.png"
    },
        "Mr P": {
            "id": 3253372688779554,
            "name": "Mr. P",
            "health": 4500,
            "attack": "1140(2)",
            "range": "7 / 10 on hit",
            "reload": "1.6 seconds",
            "movement speed": 720,
            "URL": "https://static.wikia.nocookie.net/brawlstars/images/a/a4/Mr._P_Skin-Default.png",
            "URL2": "https://static.wikia.nocookie.net/brawlstars/images/0/08/Mr._P_Portrait.png"
    },
    "Jacky": {
        "id": 833836943208183,
        "name": "Jacky",
        "health": 7500,
        "attack": 1860,
        "range": 3.33,
        "reload": "1.8 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/5/52/Jacky_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/0/03/Jacky_Portrait.png"
    },
    "Otis": {
        "id": 2835867857167275,
        "name": "Otis",
        "health": 5100,
        "attack": "660(3)",
        "range": 9,
        "reload": "1.5 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/f/fe/Otis_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/5/58/Otis_Portrait.png"
    },
    "Sam": {
        "id": 323118549697973,
        "name": "Sam",
        "health": 8100,
        "attack": "1200(2)",
        "range": 9,
        "reload": "1.6 seconds",
        "movement speed": "770-970",
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/8/87/Sam_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/f/fc/Sam_Portrait.png"
    },
    "Buzz": {
        "id": 1616012546810368,
        "name": "Buzz",
        "health": 6600,
        "attack": "630(5)",
        "range": 3,
        "reload": "1.0 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/62/Buzz_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/2/2c/Buzz_Portrait.png"
    },
    "Lou": {
        "id": 1041567651939356,
        "name": "Lou",
        "health": 4800,
        "attack": "660(3)",
        "range": 9.33,
        "reload": "1.3 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/60/Lou_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/0/0b/Lou_Portrait.png"
    },
    "Tara": {
        "id": 4308558167481917,
        "name": "Tara",
        "health": 4800,
        "attack": "660(3)",
        "range": 8,
        "reload": "2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/a/a7/Tara_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/4/49/Tara_Portrait.png"
    },
    "Colt": {
        "id": 2967056595950621,
        "name": "Colt",
        "health": 4200,
        "attack": "540(6)",
        "range": 9,
        "reload": "1.7 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/8/8a/Colt_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/0/08/Colt_Portrait.png"
    },
    "Crow": {
        "id": 3487860178354665,
        "name": "Crow",
        "health": 3600,
        "attack": "480(3)",
        "range": 8.67,
        "reload": "1.4 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/a/a2/Crow_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/6/6f/Crow_Portrait.png"
    },
    "Meg": {
        "id": 9599578289276454,
        "name": "Meg",
        "health": 3450,
        "attack": "450(2)",
        "range": 9,
        "reload": "1.3 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/e/e2/Meg_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/5/58/Meg_Portrait.png"
    },
    "Penny": {
        "id": 3743824989584912,
        "name": "Penny",
        "health": 5400,
        "attack": 1410,
        "range": 8,
        "reload": "2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/d/d6/Penny_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/8/8d/Penny_Portrait.png"
    },
    "Bonnie": {
        "id": 484758235907170,
        "name": "Bonnie",
        "health": 7200,
        "attack": "870 / 500(3)",
        "range": 9,
        "reload": "1.0 / 2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/9/90/Bonnie_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/f/f0/Bonnie_Portrait.png"
    },
    "Amber": {
        "id": 9034562693192136,
        "name": "Amber",
        "health": 4800,
        "attack": "300 per second",
        "range": 8.33,
        "reload": ".22 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/a/a3/Amber_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/9/96/Amber_Portrait.png"
    },
    "Byron": {
        "id": 319398883764392,
        "name": "Byron",
        "health": 3600,
        "attack": "510(3)",
        "range": 10,
        "reload": "1.6 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/41/Byron_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/f/f6/Byron_Portrait.png"
    },
    "Gale": {
        "id": 3435173356118277,
        "name": "Gale",
        "health": 5400,
        "attack": "420(6)",
        "range": 8.33,
        "reload": "1.4 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/1/1e/Gale_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/3/3f/Gale_Portrait.png"
    },
    "Darryl": {
        "id": 7243932602832086,
        "name": "Darryl",
        "health": 7950,
        "attack": "360(10)",
        "range": 6,
        "reload": "1.8 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/66/Darryl_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/4/46/Darryl_Portrait.png"
    },
    "Carl": {
        "id": 345955171948202,
        "name": "Carl",
        "health": 6000,
        "attack": 990,
        "range": 8.33,
        "reload": "0.5 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/46/Carl_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/1/19/Carl_Portrait.png"
    },
    "Nani": {
        "id": 4857849068924052,
        "name": "Nani",
        "health": 3900,
        "attack": "1050(3)",
        "range": 8.67,
        "reload": "1.8 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/2/20/Nani_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/c/c0/Nani_Portrait.png"
    },
    "Dynamike": {
        "id": 2485111276604730,
        "name": "Dynamike",
        "health": 4200,
        "attack": "1200(2)",
        "range": 7.33,
        "reload": "1.6 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/6e/Dynamike_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/6/64/Dynamike_Portrait.png"
    },
    "Max": {
        "id": 640886928994954,
        "name": "Max",
        "health": 4800,
        "attack": "510(4)",
        "range": 8.33,
        "reload": "1.3 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/3/33/Max_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/8/83/Max_Portrait.png"
    },
    "Grom": {
        "id": 9652135616940520,
        "name": "Grom",
        "health": 4500,
        "attack": 1740,
        "range": 7.67,
        "reload": "2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/0/0a/Grom_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/f/f5/Grom_Portrait.png"
    },
    "Ash": {
        "id": 1038451068217547,
        "name": "Ash",
        "health": 8100,
        "attack": 1200,
        "range": 4.67,
        "reload": "1.4 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/40/Ash_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/9/92/Ash_Portrait.png"
    },
    "Bibi": {
        "id": 4705115171375072,
        "name": "Bibi",
        "health": 6900,
        "attack": 2100,
        "range": 3.67,
        "reload": "0.8 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/c/c4/Bibi_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/c/c2/Bibi_Portrait.png"
    },
    "Sandy": {
        "id": 9944368316964578,
        "name": "Sandy",
        "health": 5700,
        "attack": 1290,
        "range": 6,
        "reload": "1.8 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/8/80/Sandy_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/e/e3/Sandy_Portrait.png"
    },
    "Mortis": {
        "id": 9344605301892460,
        "name": "Mortis",
        "health": 5700,
        "attack": 1350,
        "range": 2.67,
        "reload": "2.4 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/b/b2/Mortis_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/b/b4/Mortis_Portrait.png"
    },
    "Ruffs": {
        "id": 4283885865764159,
        "name": "Ruffs",
        "health": 4200,
        "attack": "840(2)",
        "range": 9,
        "reload": "1.4 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/40/Ruffs_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/6/69/Ruffs_Portrait.png"
    },
    "Bea": {
        "id": 1398940811470084,
        "name": "Bea",
        "health": 3600,
        "attack": "1200 / 3300",
        "range": 10,
        "reload": "0.9 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/7/73/Bea_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/a/ae/Bea_Portrait.png"
    },
    "Surge": {
        "id": 7776827092046450,
        "name": "Surge",
        "health": 4200,
        "attack": 1770,
        "range": "6.67 / 8.67",
        "reload": "2.0 seconds",
        "movement speed": "650-820",
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/c/cf/Surge_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/2/27/Surge_Portrait.png"
    },
    "Colette": {
        "id": 6080511861064228,
        "name": "Colette",
        "health": 5100,
        "attack": "750-2250",
        "range": 8.67,
        "reload": "1.6 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/6/63/Colette_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/e/e8/Colette_Portrait.png"
    },
    "Belle": {
        "id": 8402146846505014,
        "name": "Belle",
        "health": 3900,
        "attack": 1560,
        "range": 10,
        "reload": "1.4 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/d/d9/Belle_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/8/82/Belle_Portrait.png"
    },
    "Gene": {
        "id": 5708165258785676,
        "name": "Gene",
        "health": 5400,
        "attack": "1440 / 240",
        "range": "5.67 / 11",
        "reload": "2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/5/54/Gene_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/7/7c/Gene_Portrait.png"
    },
    "Edgar": {
        "id": 5879517537692975,
        "name": "Edgar",
        "health": 4200,
        "attack": "810(2)",
        "range": 2,
        "reload": "0.7 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/2/2b/Edgar_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/b/b4/Edgar_Portrait.png"
    },
    "Gus": {
        "id": 9583999380623130,
        "name": "Gus",
        "health": 4800,
        "attack": 1410,
        "range": 9.33,
        "reload": "1.5 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/41/Gus_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/2/2c/Gus_Portrait.png"
    },
    "Fang": {
        "id": 3824134758329442,
        "name": "Fang",
        "health": 6450,
        "attack": "525 / 2100",
        "range": "3 / 9",
        "reload": "1.0 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/48/Fang_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/b/b8/Fang_Portrait.png"
    },
    "Sprout": {
        "id": 4351427761229560,
        "name": "Sprout",
        "health": 4500,
        "attack": 1470,
        "range": 5,
        "reload": "1.7 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/e/ec/Sprout_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/4/4d/Sprout_Portrait.png"
    },
    "Buster": {
        "id": 1318541868146487,
        "name": "Buster",
        "health": 7200,
        "attack": "2220 / 1110",
        "range": 5.33,
        "reload": "1.8 seconds",
        "movement speed": 770,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/e/e3/Buster_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/a/ad/Buster_Portrait.png"
    },
    "Leon": {
        "id": 3937988613440237,
        "name": "Leon",
        "health": 4800,
        "attack": "720(4) / 288(4)",
        "range": 9.67,
        "reload": "1.9 seconds",
        "movement speed": 820,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/3/33/Leon_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/4/48/Leon_Portrait.png"
    },
    "Spike": {
        "id": 4796792848881168,
        "name": "Spike",
        "health": 3600,
        "attack":"840(6)",
        "range": 7.67,
        "reload": "2.0 seconds",
        "movement speed": 720,
        "URL": "https://static.wikia.nocookie.net/brawlstars/images/8/8e/Spike_Skin-Default.png",
        "URL2": "https://static.wikia.nocookie.net/brawlstars/images/2/22/Spike_Portrait.png"
},
"Mandy": {
    "id": 9944362334964578,
    "name": "Mandy",
    "health": 4200,
    "attack": 1800,
    "range": 9,
    "reload": "1.5 seconds",
    "movement speed": 720,
    "URL": "https://static.wikia.nocookie.net/brawlstars/images/9/95/Mandy_Skin-Default.png",
    "URL2": "https://static.wikia.nocookie.net/brawlstars/images/7/75/Mandy_Portrait.png"
},
"Chester": {
    "id": 270241420141586,
    "name": "Chester",
    "health": 4950,
    "attack": 960,
    "range": 8.33,
    "reload": "1.9 seconds",
    "movement": 770,
    "URL": "https://static.wikia.nocookie.net/brawlstars/images/4/48/Chester_Skin-Default.png",
    "URL2": "https://static.wikia.nocookie.net/brawlstars/images/3/38/Chester_Portrait.png"
},
}
module.exports = brawlers;
       